 spring:
  config:
    activate:
      on-profile: development
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-Class-Name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/facturations
    username: revenatium
    password: revenatium
  database:
    driverClassName: org.postgresql.Driver